version: 2.1

jobs:
  maven-test:
    machine: true
    steps:
      - checkout
      - run: mvn verify
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: /tmp/artifacts
          
workflows:
  my-workflow:
    jobs:
      - maven-test
      
