version: 2.1

jobs:
  maven-test:
    machine: true
    steps:
      - checkout
      - run: mvn verify
      - run:
          name: Save test results
          command: |
            ls
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
          
workflows:
  my-workflow:
    jobs:
      - maven-test
      
