version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mvn package
      - persist_to_workspace:
         root: ./
         paths:
           - target/
  maven-test:
    machine: true
    steps:
      - checkout
      - run: mvn verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit
          
workflows:
  my-workflow:
    jobs:
      - maven-test
      
